#include<stdio.h>
#include<pthread.h>
#include<semaphore.h>
#include<unistd.h>
#include<stdlib.h>
#include<time.h>

#define MAX_NUMS 3

/* The input buffer array
 * the producer and consumer threads share this buffer
 */
int buffer[MAX_NUMS];
int count = 0;

/* Thread Id for producer and consumer threads */
pthread_t producer_thread[2], consumer_thread[3];	 

/* The Mutex lock 
 * The producer and consumer threads use this lock to manage 
 * a safe shared access to the common resource, i.e. buffer 
 */
pthread_mutex_t mutex_lock;

/* Semaphore to wait on the buffer full/emtpy */
sem_t buffer_full, buffer_empty;

/*
 * The producer function
 * A random number is generated by function
 * and inserted into the shared buffer array
 */
void* producer(void* var)
{
	int i, data;
	int id = (int)var;    

for (i = 0; i < MAX_NUMS; i++)
{
    		srand(time(NULL));
    		data = (rand() % 100) + 1;

    		sem_wait(&buffer_empty);
    		/* Acquire the lock before accessing the shared buffer */
    		pthread_mutex_lock(&mutex_lock);
  		 
    		printf("\nProducer %d produced: %d\n", id, data);
    		buffer[count] = data;
    		count++;

    		pthread_mutex_unlock(&mutex_lock);
    		sleep(2);
    		sem_post(&buffer_full);
}
	printf("\nExit Producer thread\n");
}

/*
 * The consumer method
 * Items are removed from the common buffer array using this function
 */
void* consumer(void* var)
{
int data, i;
	int id = (int)var;

	for (i = 0; i < MAX_NUMS; i++)
{   	 
    		sem_wait(&buffer_full);
    		pthread_mutex_lock(&mutex_lock);
   	 
    		data = buffer[count - 1];
    		count--;
    		printf("\nConsumer %d consumed: %d\n", id, data);

    		pthread_mutex_unlock(&mutex_lock);
    		sleep(2);
    		sem_post(&buffer_empty);
	}
	printf("\nExit Consumer thread\n");
}

int main()
{
pthread_mutex_init(&mutex_lock, NULL);
    	sem_init(&buffer_full, 0, 0);
    	sem_init(&buffer_empty, 0, MAX_NUMS);
    

    	/* Produces threads */
    	pthread_create(&producer_thread[0], NULL, producer, (void*)(1));  
    	pthread_create(&producer_thread[1], NULL, producer, (void*)(2));  
    
    	/* Consumer threads */
    	pthread_create(&consumer_thread[0], NULL, consumer, (void*)(1));  
    	pthread_create(&consumer_thread[1], NULL, consumer, (void*)(2));
    
    	/* joining all the threads */
	pthread_join(producer_thread[0], NULL);
    	pthread_join(producer_thread[1], NULL);
   	pthread_join(consumer_thread[0], NULL);
pthread_join(consumer_thread[1], NULL);

    	pthread_exit(NULL);
}
